I use bc during make_all and was not checking for it centos really is barebones... adding `patch` to the list of dependencies make_all.py needs adding additional python modules that other applications need in order to test properly centos needs bzip2. Which is not installed by default openmpi is causing issues on linux machines. Switch to mpich by default for now
Turns out, the sed command was failing and ending up allowing: `cd *` which amazingly worked for so long undetected.
With this latest change, we are using an additional binary. Adding `uniq` to the list of requirements.

diff --git a/build_from_source/functions b/build_from_source/functions
--- a/build_from_source/functions
+++ b/build_from_source/functions
@@ -31,7 +31,14 @@ extract() {
 	    cleanup 1
 	fi
     done
-    cd $(echo ${EXTRACT[0]} | sed -e 's/[^a-zA-z]/ /g' | cut -d\  -f1)*
+    # Lets hope the tarballs were created correctly
+    cd $(tar -tzf $DOWNLOAD_DIR/${EXTRACT[0]} | sed -e 's@/.*@@' | uniq)
+    if [ $? -ne 0 ]; then
+	echo -e 'Failed to determine which directory to `cd` into'
+	cleanup 1
+    else
+	echo -e 'Entered build directory: '`pwd`
+    fi
 }
 
 configure() {
